version: '3.1'

services:
  logrdb:
    image: gnakor/logrdb
    environment:
      - LOGRDB_MODE=local
      - LOGRDB_USERNAME=admin
      - LOGRDB_PASSWORD=123456
    ports:
      - "6114:44000"

  php:
    build: docker/php
    #image: dunglas/frankenphp
    # uncomment the following line if you want to use a custom Dockerfile
    #build: .
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    #stdin_open: true
    #tty: true
    environment:
      DB_HOST: bdd
      DB_USER_NAME: root
      DB_USER_PASSWORD: 123456
      DB_NAME: library

      CACHE_HOST: redis

      LOGRDB_IP: logrdb
      LOGRDB_LEVEL: debug
      LOGRDB_SQL: all
      LOGRDB_HTTP: all
      LOGRDB_APP_NAME: book_php_sample

      MAILER_DNS: mailer

      APP_NAME: TEMPLATE-APP
      JWT_SECRET: dzI6nbW4OcNF-AtfxGAmuyz7IpHRudBI0WgGjZWgaRJt6prBn3DARXgUR8NVwKhfL43QBIU2Un3AvCGCHRgY4TbEqhOi8-i98xxmCggNjde4oaW6wkJ2NgM3Ss9SOX9zS3lcVzdCMdum-RwVJ301kbin4UtGztuzFrancois00MGxjC2xWwyI0tgXVs-zJs5WlafCuGfX1HrVkIf5bvpE0MQCSjdJpSeVao6-RSTYDajZf7T88a2eVjeW31mMAg-jzAWfUrii61T_bYPJFOXW8kkRWoa1InLRdG6bKB9wQs9-VdXZP60Q4Yuj_WZ-lO7qV9AEFrUkkjpaDgZT86w2g
    ports:
      - "6108:80"
      - "6109:443"
    volumes:
      - ./app:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    links:
      - logrdb
      - bdd
      - mailer

  bdd:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=library
      - MYSQL_USER=client
      - MYSQL_PASSWORD=123456
    command: --sql_mode=""
    ports:
      - "3313:3306"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      DEBUG: 1
      PMA_HOSTS: bdd
      UPLOAD_LIMIT: 300M
    ports:
      - "6104:80"
    depends_on:
      - bdd
    links:
      - bdd

  redis:
    image: "redis:alpine"
    ports:
      - "5000:6379"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"